---
extends: default

rules:
  line-length: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  trailing-spaces: enable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  empty-lines:
    max: 1
